name: BUILD

on:
  schedule:
    - cron:  '* */6 * * *'
  status:
  issues:
    types: [opened, edited, milestoned]


jobs:
  build:
    strategy:
      matrix:
        repos: [python-powerline-git, osu-lazer, lemon-lime-git, systemd-cleanup-pacman-hook, librime-lua-git, mystiq]

      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: DuckSoft/build-aur-action@master
      with:
        repo-name: ${{ matrix.repos }}
    
    - uses: ncipollo/release-action@v1.6.1
      with:
        allowUpdates: true
        tag: "packages"
        artifacts: "./*/*.xz"
        token: ${{ secrets.GITHUB_TOKEN }}
