name: BUILD

on:
  schedule:
    - cron:  '* */6 * * *'
  status:
  push:
    branches: master
  issues:
    types: [opened, edited, milestoned]


jobs:
  build:
    strategy:
      matrix:
        repos: [r8125, osu-lazer, systemd-cleanup-pacman-hook, fcitx5-skin-adwaita-dark, fcitx5-skin-base16-material-darker, fcitx5-skin-dark-numix, fcitx5-skin-dark-transparent, fcitx5-skin-materia-exp, lemon-lime, lemon-lime-git, rime-aurora-pinyin, rime-essay-simp, rime-opencc-emoji-symbols]

      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: DuckSoft/build-aur-action@master
      with:
        repo-name: ${{ matrix.repos }}
    
    - uses: ncipollo/release-action@v1.6.1
      with:
        allowUpdates: true
        tag: "packages"
        artifacts: "./*/*.zst"
        token: ${{ secrets.GITHUB_TOKEN }}
